/// The configuration file is automatically generated by the plugin. Please do not modify its contents.

export default {
  Assistant: {
    name: 'Assistant',
    component: () => import('@/pages/Assistant/index.tsx'),
    mfKey: './src/pages/Assistant/index.tsx',
  },
  AssistantHistory: {
    name: 'AssistantHistory',
    component: () => import('@/pages/AssistantHistory/index.tsx'),
    mfKey: './src/pages/AssistantHistory/index.tsx',
  },
  Bulk: {
    name: 'Bulk',
    component: () => import('@/pages/Bulk/index.tsx'),
    mfKey: './src/pages/Bulk/index.tsx',
  },
  FinancialReports: {
    name: 'FinancialReports',
    component: () => import('@/pages/FinancialReports/index.tsx'),
    mfKey: './src/pages/FinancialReports/index.tsx',
  },
  Knowledge: {
    name: 'Knowledge',
    component: () => import('@/pages/Knowledge/index.tsx'),
    mfKey: './src/pages/Knowledge/index.tsx',
  },
  Login: {
    name: 'Login',
    component: () => import('@/pages/Login/index.tsx'),
    mfKey: './src/pages/Login/index.tsx',
  },
} satisfies Record<string, { name: string; component: () => Promise<any>; mfKey: string }>;
