export const optionCpiPpi: echarts.EChartsCoreOption = {
  backgroundColor: 'transparent',
  color: ['#2F81F7', '#7C6AF2'],
  tooltip: {
    trigger: 'axis',
    axisPointer: { type: 'line' },
    valueFormatter: (v: null) => (v == null ? '' : `${v}%`),
  },
  legend: {
    bottom: 8,
    icon: 'roundRect',
    itemHeight: 4,
    itemWidth: 16,
    textStyle: { color: '#596375' },
    data: ['中国:CPI:当月同比', '中国:PPI:全部工业品:当月同比'],
  },
  grid: { left: 0, right: 0, top: 10, bottom: 48, containLabel: true },
  xAxis: {
    type: 'category',
    boundaryGap: false,
    axisLine: { lineStyle: { color: '#D7E0EE' } },
    axisTick: { show: false },
    axisLabel: { color: '#596375' },
    data: [
      '24/01',
      '24/03',
      '24/05',
      '24/07',
      '24/09',
      '24/11',
      '25/01',
      '25/03',
      '25/05',
      '25/07',
    ],
  },
  yAxis: {
    type: 'value',
    min: -4.2,
    max: 0.2,
    interval: 0.7,
    axisLabel: { formatter: '{value} %', color: '#596375' },
    splitLine: { lineStyle: { color: '#EEF3FA' } },
    axisLine: { show: false },
    axisTick: { show: false },
  },
  series: [
    {
      name: '中国:CPI:当月同比',
      type: 'line',
      smooth: false,
      symbol: 'circle',
      symbolSize: 4,
      showSymbol: false,
      lineStyle: { width: 2 },
      data: [-2.6, -0.4, -0.2, -0.1, -0.1, -0.1, -1.0, -0.3, -0.3, -0.2],
    },
    {
      name: '中国:PPI:全部工业品:当月同比',
      type: 'line',
      smooth: false,
      symbol: 'circle',
      symbolSize: 4,
      showSymbol: false,
      lineStyle: { width: 2 },
      data: [-2.8, -2.6, -1.0, -0.7, -2.7, -2.5, -2.4, -2.4, -3.1, -3.1],
    },
  ],
};

export const optionPMI: echarts.EChartsCoreOption = {
  backgroundColor: 'transparent',
  color: ['#2F81F7', '#7C6AF2'],
  tooltip: {
    trigger: 'axis',
    axisPointer: { type: 'line' },
    valueFormatter: (v: null) => (v == null ? '' : `${v}`),
  },
  legend: {
    bottom: 8,
    icon: 'roundRect',
    itemHeight: 4,
    itemWidth: 16,
    textStyle: { color: '#596375' },
    data: ['中国:制造业PMI', '中国:服务业PMI'],
  },
  grid: { left: 0, right: 0, top: 10, bottom: 48, containLabel: true },
  xAxis: {
    type: 'category',
    boundaryGap: false,
    axisLine: { lineStyle: { color: '#D7E0EE' } },
    axisTick: { show: false },
    axisLabel: { color: '#596375' },
    data: [
      '24/01',
      '24/03',
      '24/05',
      '24/07',
      '24/09',
      '24/11',
      '24/12',
      '25/02',
      '25/04',
      '25/06',
      '25/08',
    ],
  },
  yAxis: {
    type: 'value',
    min: 49.2,
    max: 52.8,
    interval: 0.6,
    axisLabel: { formatter: '{value} %', color: '#596375' },
    splitLine: { lineStyle: { color: '#EEF3FA' } },
    axisLine: { show: false },
    axisTick: { show: false },
  },
  series: [
    {
      name: '中国:制造业PMI',
      type: 'line',
      smooth: false,
      symbol: 'circle',
      symbolSize: 4,
      showSymbol: false,
      lineStyle: { width: 2 },
      data: [49.7, 50.9, 50.1, 49.6, 49.4, 49.8, 52.6, 49.0, 50.6, 49.7, 50.2],
    },
    {
      name: '中国:服务业PMI',
      type: 'line',
      smooth: false,
      symbol: 'circle',
      symbolSize: 4,
      showSymbol: false,
      lineStyle: { width: 2 },
      data: [49.8, 50.5, 49.4, 49.3, 49.2, 50.1, 49.4, 49.6, 50.9, 49.4, 49.8],
    },
  ],
};
